### PR TITLE
show original files on development 

### PR DESCRIPTION
**Pull request by wesleyalcoforado**
Hi, I made some changes in the plugin, in order to make it show the uncompressed files when on development. Maybe you'd like to incorporate these changes in your code.

Att.,
Wesley

### CODE REVIEW

**Comment by digitarald** [comment]
Love the objective. Dev environment should not use compressed or combined files at all to allow debugging. The combine logic should be optionally disabled and output one include tag for each file.

**Comment by digitarald** [comment]
Will you consider this implementation or should I start my own? Development is pretty much stuck when I need to compile my files all the time for every change.

**Comment by rande** [comment]
There is actually no easy way to make the plugin "disable" the compression. config_handler.yml is one of the first files being read by symfony (before plugin). 

The only way to disable compression is to restore the default config handler ... unless you have a better solution. I need to review this patch before integrated this into the plugin.

@digitarald : If you want to contribute to this plugin, I have one pretty good idea : http://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by digitarald** [comment]
I rather add support for LESS/SASS and pngcrush ;)

**Comment by digitarald** [comment]
About no-easy-way: aren't config files build on every call when in dev mode? So the check could be in the config file handler, I will experiment a bit.

**Comment by rande** [comment]
@digitarald : the config files are read once ...

**Comment by digitarald** [comment]
See http://github.com/rande/swCombinePlugin/issues#issue/6

**Comment by rande** [comment]
done from another commit https://github.com/rande/swCombinePlugin/commit/08ffbead1e5773d3eff37dc6f6bc6441014906d0

**Pull request closed without merging**
